name: Build Repo Listing
on:
  release:
    types:
      - created
      - deleted
      - edited
      - published
      - released
      - unpublished
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    workflows:
      - Build Release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: write
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  website:
    secrets: inherit
    uses: ./.github/workflows/build-website.yml
    with:
      listPublishDirectory: Website
      pathToCi: ci

  deploy:
    needs: website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download listing artifact
        uses: actions/download-artifact@v4
        with:
          name: listing-site
          path: Website
      - name: Prepare for GitHub Pages deployment
        uses: actions/configure-pages@v5
        with:
          enablement: true
          token: ${{ secrets.REPO_TOKEN }}
      - name: Upload the VPM Listing Website to GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: Website
      - id: deployment
        name: Deploy the uploaded VPM Listing Website to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Trigger the action of the curation repository
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build-listing
          repository: kurone-kito/vpm
          token: ${{ secrets.REPO_TOKEN }}
