concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
name: The CI workflow on push
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Local Repository
        uses: actions/checkout@v4
      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v7
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
  package:
    permissions:
      actions: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/package-build.yml
    with:
      packagePath: Packages/${{ vars.PACKAGE_NAME }}
      unityPackage: ${{ vars.PACKAGE_NAME }}-feature.unitypackage
      zipFile: ${{ vars.PACKAGE_NAME }}-feature.zip
  website:
    needs: package
    permissions:
      actions: write
      contents: read
    uses: ./.github/workflows/build-website.yml
    with:
      listPublishDirectory: Website
      pathToCi: ci
      zipFile: ${{ vars.PACKAGE_NAME }}-feature.zip
      unityPackage: ${{ vars.PACKAGE_NAME }}-feature.unitypackage
